### PR TITLE
Tracking eval BEV visualization

### PR DESCRIPTION
**Pull request by cdicle-nutonomy**
This PR implements a BEV visualization for the scenes and objects. It exposes the functionality to the user to help debugging and subjective assessment of tracking performance. User needs to input the list of classes to visualize. Example usage
```
python evaluate.py result_path --output_dir output_path --render_classes car bus 
```
Example output: 

The output is generated from vehicle coordinate system. The tracking boxes are augmented with vehicle based coordinates in order to achieve this effect. 

The black boxes represent ground truth and colored boxes are predictions where each prediction is associated with a unique color. The switches are highlighted by changing front and the back border of the object to red.

### CODE REVIEW

**Comment by zzm-hl** [comment]
Can I combine the tracking in the same folder on one chart, how do I do that?

**Comment by zzm-hl** [comment]
my computer is 16GB RAM，when I run the `python evaluate.py result_path  --render_classes car  ` it seems Processes are killed.  `--render_classes` will take up a lot of memory. how can i solve it .  @holger-motional

**Comment by whyekit-motional** [comment]
@zzm-hl try adding `fig.clf()` just before this line and see if it works for you: https://github.com/nutonomy/nuscenes-devkit/blob/f94dcd313feb8adc91e7d01312fb7d27cc77098e/python-sdk/nuscenes/eval/tracking/render.py#L166

**Comment by zzm-hl** [comment]
> 

I tried, but this doesn't seem to work, it still says killed

**Comment by zzm-hl** [comment]
> @zzm-hl try adding `fig.clf()` just before this line and see if it works for you:
> 
> https://github.com/nutonomy/nuscenes-devkit/blob/f94dcd313feb8adc91e7d01312fb7d27cc77098e/python-sdk/nuscenes/eval/tracking/render.py#L166

Hello, I solved the previous problem by increasing the memory, but I have a new question, can I draw different frames of the same video on the same picture in a row? It used to save one picture for each frame

**Comment by whyekit-motional** [comment]
@zzm-hl for questions / clarifications, pls open an issue under https://github.com/nutonomy/nuscenes-devkit/issues so as not to crowd the conversation section of this PR (the conversation section is generally reserved for comments directly related to _changes_ made in the specific PR)

**Comment by zzm-hl** [comment]
> @zzm-hl for questions / clarifications, pls open an issue under https://github.com/nutonomy/nuscenes-devkit/issues so as not to crowd the conversation section of this PR (the conversation section is generally reserved for comments directly related to _changes_ made in the specific PR)

OKay, thanks~

**Pull request merged**
