### PR TITLE
add ReLU activation function after each linear layer in CoverNet model

### PR DESCRIPTION
**Pull request by Mohammed-Deifallah**
After discussing this issue with [Erik Wolff](https://github.com/emwolff), he asked me to create a pull request with this slight change in order to add a non-linearity to the provided CoverNet model.

### CODE REVIEW

**Review by emwolff — APPROVED** [review]

**Comment by emwolff** [comment]
@Mohammed-Deifallah  or @whyekit-motional  can you please fix the indent when you have a moment? Thanks.

**Comment by Mohammed-Deifallah** [comment]
Dear Eric @emwolff,
I've just created a new PR with this fix.
Thanks,

**Comment by whyekit-motional** [comment]
@Mohammed-Deifallah this PR (#758) looks exactly the same as #760 now that the indentation has been fixed here as well - can you close #760 and I'll merge #758?

**Comment by Mohammed-Deifallah** [comment]
@whyekit-motional They just look the same, but they are not. Anyway, I will close it if you managed to fix this on your side.

**Pull request merged**
