### PR TITLE
Loading large json files (modified version of #439)

### PR DESCRIPTION
**Pull request by holger-nutonomy**
This PR is a minor modification of https://github.com/nutonomy/nuscenes-devkit/pull/439, but it makes ijson entirely optional.

### CODE REVIEW

**Comment by holger-nutonomy** [comment]
@miraliahmadli Here is a slightly modified version of your code that only uses ijson if it is installed.
I've tried to benchmark this in a very primitive way.
Loading time is printed by the code, RAM usage comes from the default Ubuntu system monitor and for RAM overload I loaded two instances of the NuScenes class on a machine with 32GB of RAM and checked if it gets killed due to a lack of memory.
1) Loading time: json: 41s vs. ijson: 46s (worse)
2) RAM usage: json: 13.3GB vs. ijson: 13.0GB (same)
3) RAM overload: json: no vs. ijson: yes (worse)
To me ijson looks worse. I'd be okay if loading time or RAM usage would be a slightly impacted, but the fact that using ijson is more likely to kill the process on my machine is not good. @Qiang-Xu @oscar-nutonomy 

@miraliahmadli Do you mind giving this code a few tries on your machine?
The snippet used to test it was:
```
from nuscenes.nuscenes import NuScenes
nusc = NuScenes(version='v1.0-trainval')
nusc2 = NuScenes(version='v1.0-trainval')
```

**Comment by holger-nutonomy** [comment]
@miraliahmadli Do you mind taking a look?

**Comment by miraliahmadli** [comment]
@holger-nutonomy Thanks for checking my PR. I encountered the issue when I was trying to explore the dataset. It happened only in sample data file (due to size of file I guess) and I did this quick fix. I was using machine with 32GB  RAM.

Unfortunately, I no longer have access to the computing power to test this again. So, you may ignore the PR.

**Comment by holger-nutonomy** [comment]
@miraliahmadli Thanks for the reply. We'll close this PR for now, but if anyone else thinks it helps, we can add it in the future.

**Pull request closed without merging**
